FROM golang:1.12

ADD ./cmd/server /go/src/app
WORKDIR /go/src/app

ENV GO111MODULE=on

COPY go.mod .
COPY go.sum .

RUN go mod download

ENV PORT=8080
ENV REQUESTDIRECTORY=requests

CMD ["go", "run", "main.go"]